In [1]:
import numpy as np

In [2]:
np.random.seed(0)
np.random.randint(low=1, high=100, size=10)

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [3]:
np.random.seed(5)
np.random.randint(low=1, high=100, size=10)

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8])

In [4]:
np.random.seed(5)
np.random.randint(low=1, high=100, size=10)

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8])

In [5]:
np.random.seed(0)
np.random.randint(low=1, high=100, size=10)

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

- random_state is feed into the equation that starts the sequence of random numbers. The same seed will give the same sequence of randomness.

- So, it is not so “random”, it is pseudorandom controlled by a mathematical function.